name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'   # Workflow uruchomi się przy wypchnięciu tagu w formacie np. v1.0.0

jobs:
  build:
    runs-on: windows-latest  # Budujemy na Windowsie, aby wygenerować plik .exe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'     # Możesz wybrać wersję Node, której potrzebujesz
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application (frontend)
        run: npm run build     # Jeśli masz osobny skrypt budujący front-end

      - name: Package application with electron-builder
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
