name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Uruchamia się, gdy pushujesz tagi wersji, np. "v1.0.0"
  workflow_dispatch:  # Umożliwia ręczne uruchomienie workflow
jobs:
  build:
    runs-on: windows-latest  # Używamy Windowsa do budowania exe
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Debug dist folder
        run: ls -R dist  # Wyświetl zawartość folderu dist

      - name: Package app for Windows
        run: npx electron-builder --win --publish never

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PoliTest-windows
          path: dist/*.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
